services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/im-yuuki/ticketrushserver:master
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PGSQL_URL=jdbc:postgresql://postgres:5432/ticketrush
      - PGSQL_USR=ticketrush
      - PGSQL_PWD=ticketrush
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - compose.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ticketrush
      - POSTGRES_USER=ticketrush
      - POSTGRES_PASSWORD=ticketrush
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  elasticsearch:
    image: elasticsearch:latest
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    volumes:
      - esdata:/usr/share/elasticsearch

volumes:
  pgdata:
  esdata:

networks:
  default:
    enable_ipv6: true
