export const emailTheme = {
  font: {
    body: "Google Sans, Roboto, Inter, Segoe UI, Arial, Helvetica, sans-serif",
    brand: "Nunito, Google Sans, Roboto, Inter, Segoe UI, Arial, Helvetica, sans-serif",
    code: "Google Sans Code, Roboto Mono, SFMono-Regular, Consolas, Liberation Mono, monospace",
  },
  color: {
    light: {
      accent: "#c48a12",
      background: "#ffffff",
      border: "#dadce0",
      card: "#ffffff",
      cardSecondary: "#f8f9fa",
      foreground: "#202124",
      muted: "#5f6368",
      outline: "#e8eaed",
      otpBackground: "#ffffff",
      otpForeground: "#202124",
      shadow: "none",
      subtleShadow: "none",
    },
    dark: {
      accent: "#d6a22d",
      background: "#000000",
      border: "#2f3033",
      card: "#111111",
      cardSecondary: "#181818",
      foreground: "#f1f3f4",
      muted: "#bdc1c6",
      outline: "#3c4043",
      otpBackground: "#101010",
      otpForeground: "#ffffff",
      shadow: "none",
      subtleShadow: "none",
    },
  },
  radius: {
    shell: 12,
    card: 10,
    otp: 8,
  },
  spacing: {
    shellInset: 24,
    cardInsetX: 28,
    cardInsetY: 32,
  },
} as const;
