app:
  jwt:
    secret: ${JWT_SEC:}
    access-token-expiration: 86400
  s3:
    api: ${S3_API}
    bucket: ${S3_BUCKET}
    access-id: ${S3_ID}
    secret-key: ${S3_SEC}
  mail: ${MAIL_ADDR}
  proxied: ${APP_PROXIED:false}

server:
  servlet:
    context-path: /api/v1
  http2:
    enabled: true
  port: 8080

spring:
  application:
    name: TicketRushServer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PGSQL_URL:jdbc:postgresql://localhost:5432/ticketrush}
    username: ${PGSQL_USR:ticketrush}
    password: ${PGSQL_PWD:ticketrush}
  data:
    redis:
      client-name: ticketrush-server
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:}
      database: ${REDIS_DB:0}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_schema: ${PGSQL_SCH:public}
    open-in-view: true
  mail:
    test-connection: true
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USR}
    password: ${SMTP_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  output:
    ansi:
      enabled: always
  cache:
    type: redis
    redis:
      key-prefix: "ticketrush:cache:"
      use-key-prefix: true
      time-to-live: 300s

logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] %clr(%-5level) %blue(%-40.40logger{39}) : %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] %-5level %-40.40logger{39} : %msg%n"
  level:
    me.june8th.ticketrushserver: trace
    root: info
