server:
  servlet:
    context-path: /api/v1
  http2:
    enabled: true
  port: 8080

spring:
  application:
    name: TicketRushServer
    version: 0.0.1-SNAPSHOT
  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: true
      client-name: ticketrush-server
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:}
      database: ${REDIS_DB:0}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketrush}
    username: ${DB_USR:ticketrush}
    password: ${DB_PWD:}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_schema: v1
    show-sql: false
  output:
    ansi:
      enabled: always
