###
POST https://TicketRushServer/v1/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

###
POST https://TicketRushServer/v1/auth/logout

###
POST https://TicketRushServer/v1/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": "",
  "birthDate": "",
  "gender": "MALE"
}

###
GET https://TicketRushServer/v1/auth/register/confirmation
Content-Type: application/json

{
  "otpCode": ""
}

###
POST https://TicketRushServer/v1/auth/register/confirmation
Content-Type: application/json

###
POST https://TicketRushServer/v1/auth/reset
Content-Type: application/json

{
  "email": "",
  "newPassword": ""
}

###
GET https://TicketRushServer/v1/auth/reset/confirm
Content-Type: application/json

{
  "otpCode": ""
}

###
POST https://TicketRushServer/v1/auth/reset/confirm
Content-Type: application/json

###
GET https://TicketRushServer/v1/feeds/promoted

###
GET https://TicketRushServer/v1/feeds/recommendeds

###
GET https://TicketRushServer/v1/feeds/trending

###
GET https://TicketRushServer/v1/public/event/{{id}}

###
GET https://TicketRushServer/v1/public/org/@{{alias}}

###
GET https://TicketRushServer/v1/public/org/{{id}}

###
GET https://TicketRushServer/v1/account

###
PUT https://TicketRushServer/v1/account/email
Content-Type: application/json

{
  "newEmail": "",
  "currentPassword": ""
}

###
POST https://TicketRushServer/v1/account/logout-all

###
PUT https://TicketRushServer/v1/account/name
Content-Type: application/json

{
  "newName": ""
}

###
PUT https://TicketRushServer/v1/account/password
Content-Type: application/json

{
  "currentPassword": "",
  "newPassword": ""
}

###
PUT https://TicketRushServer/v1/organization/avatar?
    file={{$random.alphanumeric(8)}}

###
PUT https://TicketRushServer/v1/organization/banner?
    file={{$random.alphanumeric(8)}}

###
GET https://TicketRushServer/v1/organization/events
Content-Type: application/json

{
  "name": "",
  "description": "",
  "isOnlineEvent": false,
  "venue": "",
  "address": "",
  "dateTime": {}
}

###
POST https://TicketRushServer/v1/organization/events
Content-Type: application/json

###
GET https://TicketRushServer/v1/organization/events/{{eventId}}
Content-Type: application/json

{
  "name": "",
  "description": "",
  "isOnlineEvent": false,
  "venue": "",
  "address": "",
  "dateTime": {}
}

###
PATCH https://TicketRushServer/v1/organization/events/{{eventId}}
Content-Type: application/json

###
DELETE https://TicketRushServer/v1/organization/events/{{eventId}}
Content-Type: application/json

{
  "name": "",
  "description": "",
  "isOnlineEvent": false,
  "venue": "",
  "address": "",
  "dateTime": {}
}

###
PUT https://TicketRushServer/v1/organization/events/{{eventId}}/banner?
    file={{$random.alphanumeric(8)}}

###
POST https://TicketRushServer/v1/organization/events/{{eventId}}/publish

###
POST https://TicketRushServer/v1/organization/events/{{eventId}}/sales-rounds
Content-Type: application/json

{
  "name": "",
  "startTime": {},
  "endTime": {},
  "maxTicketsPerPurchase": 0
}

###
PATCH https://TicketRushServer/v1/organization/events/{{eventId}}/sales-rounds/{{roundId}}
Content-Type: application/json

{
  "name": "",
  "startTime": {},
  "endTime": {},
  "maxTicketsPerPurchase": 0
}

###
DELETE https://TicketRushServer/v1/organization/events/{{eventId}}/sales-rounds/{{roundId}}
Content-Type: application/json

{
  "name": "",
  "startTime": {},
  "endTime": {},
  "maxTicketsPerPurchase": 0
}

###
POST https://TicketRushServer/v1/organization/events/{{eventId}}/seat-zones
Content-Type: application/json

{
  "name": "",
  "positionX": 0,
  "positionY": 0,
  "rows": []
}

###
DELETE https://TicketRushServer/v1/organization/events/{{eventId}}/seat-zones/{{zoneId}}

###
POST https://TicketRushServer/v1/organization/events/{{eventId}}/staff
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": ""
}

###
DELETE https://TicketRushServer/v1/organization/events/{{eventId}}/staff/{{staffId}}

###
POST https://TicketRushServer/v1/organization/events/{{eventId}}/ticket-classes
Content-Type: application/json

{
  "name": "",
  "description": "",
  "price": 0,
  "salesRoundId": 0,
  "seatZoneId": 0
}

###
DELETE https://TicketRushServer/v1/organization/events/{{eventId}}/ticket-classes/{{ticketClassId}}

###
GET https://TicketRushServer/v1/organization/info
Content-Type: application/json

{
  "description": "",
  "aliasName": "",
  "websiteUrl": ""
}

###
PATCH https://TicketRushServer/v1/organization/info
Content-Type: application/json

###
POST https://TicketRushServer/v1/checkin
Content-Type: application/json

{
  "eventId": 0,
  "ticketId": 0,
  "userId": 0,
  "ticketSecretCode": ""
}

###
GET https://TicketRushServer/v1/purchase/event/{{eventId}}

###
POST https://TicketRushServer/v1/purchase/hold
Content-Type: application/json

{
  "eventId": 0,
  "items": []
}

###
GET https://TicketRushServer/v1/purchase/hold/{{holdId}}

###
DELETE https://TicketRushServer/v1/purchase/hold/{{holdId}}

###
POST https://TicketRushServer/v1/purchase/pay/{{holdId}}

###
GET https://TicketRushServer/v1/user
Content-Type: application/json

{
  "birthDate": "",
  "gender": "MALE",
  "phoneNumber": "",
  "addressLine": ""
}

###
PATCH https://TicketRushServer/v1/user
Content-Type: application/json

{
  "birthDate": "",
  "gender": "MALE",
  "phoneNumber": "",
  "addressLine": ""
}

###
PUT https://TicketRushServer/v1/user/avatar?
    file={{$random.alphanumeric(8)}}

###
PUT https://TicketRushServer/v1/user/follow/{{id}}

###
DELETE https://TicketRushServer/v1/user/follow/{{id}}

###
GET https://TicketRushServer/v1/user/tickets

###
POST https://TicketRushServer/v1/admin/account/{{id}}/lock

###
POST https://TicketRushServer/v1/admin/account/{{id}}/unlock

###
POST https://TicketRushServer/v1/admin/organization/{{id}}/verify

###
PUT https://TicketRushServer/v1/admin/organizations
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": ""
}