name: Build Executable JAR
on:
  push:
  pull_request:
    branches: [main, master]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          java-version: '25'

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test --no-daemon

      - name: Upload JAR Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v7
        with:
          name: ticketrush-server-jar-${{ github.sha }}
          path: build/libs/*.jar

      - name: Upload JAR to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
